name: NixOS Validation

on:
  push:
    branches: [ 'main' ]
    paths:
      - '**.nix'
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/**'

  pull_request:
    branches: [ 'main' ]
    paths:
      - '**.nix'
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/**'

jobs:
  validate:
    name: Validate NixOS config via Docker
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t nixos-validate .

      - name: Run validation in container
        run: docker run --rm nixos-validate
