name: NixOS Validation

on:
  push:
    branches: [ 'main' ]
    paths:
      - '**.nix'
      - 'flake.*'
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/**'

  pull_request:
    branches: [ 'main' ]
    paths:
      - '**.nix'
      - 'flake.*'
      - 'Dockerfile'
      - '.dockerignore'
      - '.github/workflows/**'

concurrency:
  group: nixos-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  flake-check:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: experimental-features = nix-command flakes

      - name: Flake checks (light)
        run: nix flake check --print-build-logs

  eval-hosts:
    needs: flake-check
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        host:
          - oniguruma
          - capybara
          - hellicopter
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: experimental-features = nix-command flakes

      - name: Eval NixOS drv (no build) for ${{ matrix.host }}
        run: nix eval .#nixosConfigurations.${{ matrix.host }}.config.system.build.toplevel.drvPath
